### ISSUE TITLE
Licence of database

### ISSUE THREAD

**Issue by nozmajner** [astronexus/HYG-Database#11]
Hi!
I would like to ask, what's the licensing for the HYG database? Is it GNU GPL v3 or CC-BY-SA-3.0 compatible?
I'm asking because we are thinking about incorporating it into [Pioneer](https://pioneerspacesim.net), if it has a compatible license.

Thank you!

**Comment by kbahey** [comment]
Same question, and same use case. The application in question is OnStep's Smart Hand Controller, and is GPL licensed.

**Comment by astronexus** [comment]
I have updated the README with the current licensing information.

**Comment by nozmajner** [comment]
Thank you!
