### ISSUE TITLE
Right Ascension Values Are Incorrect

### ISSUE THREAD

**Issue by jfcarr** [astronexus/HYG-Database#12]
The Right Ascension values do not appear to be correct.  The conversion of RA from hh:mm:ss format to decimal should be as follows:

`RA in degrees = (hours x 15) + (minutes / 4) + (seconds / 240)`

But, it looks like it was done without the x15.  For example, the RA for Sirius in the .csv file is 6.7525694, which is incorrect, but multiplying it by 15 yields the correct value: 101.288541.

**Comment by astronexus** [comment]
The RA field is in decimal hours, not degrees. This is a common decimal alternative to degrees for RA because it can still be found easily on a star chart. I’ll update the readme soon to clarify that.

**Comment by jfcarr** [comment]
Thanks, I wondered if that might be the intention after I submitted the ticket.  My apologies for not inquiring first.  I encountered the issue when I tried to consume the values directly in AstroPy.
