### ISSUE TITLE
comp and comp_primary are invalid

### ISSUE THREAD

**Issue by pdyxs** [astronexus/HYG-Database#15]
Right now 'comp' is 1 for every star, and 'comp_primary' is the current star's id

**Comment by astronexus** [comment]
comp > 1 is currently only defined for multiple stars with a Gliese catalog ID, which is a fairly small subset. 

Example: HYG 162 = Gliese 914B; this has comp=2 (since it's the "B" star in the system) and comp_primary = 171 (the HYG ID of Gliese 914A, the primary star in the system).

**Comment by pdyxs** [comment]
Ah right, that makes a lot more sense. Thanks!
