### ISSUE TITLE
Missing Entry

### ISSUE THREAD

**Issue by meawoppl** [astronexus/HYG-Database#24]
The catalogue `hygdata_v3.csv` skips between entries 118139 and 118141 omitting one entry.

I suspect this is unintentional, as the sequence of ID's is otherwise unbroken.

**Comment by meawoppl** [comment]
Further inspection has revealed that entry #118329 is also missing.

**Comment by astronexus** [comment]
This is looking like a simple error in the numbering, not missing data.

The two catalog entries on either side of the missing ID are:

HYG 118139 = NN 3153
HYG 118141 = NN 3156

where "NN" is an obsolete label for an addition to the Gliese catalog (later versions of HYG use "GJ" for these).

These two entries occur in a block of data that came entirely from the Gliese catalog (no HIP or HR numbers) in RA order. As a result, I checked the Gliese catalog for the nearby catalog entries in RA to see if one of them was missing, a sign that a row had been accidentally deleted at some point. They are, in order:

NN 3153 = HYG 118139
NN 3154
Gl  96
Wo 9079
NN 3155
Gl  97 
Gl  97.1
NN 3156 = HYG 118141

All entries between NN 3153 and NN 3156 are accounted for elsewhere in the catalog (specifically, they all corresponded to a star with a HIP ID).  

A similar analysis for the stars adjacent to the ID 118329 also shows all Gliese stars in the appropriate RA range are accounted for.

I don't know exactly what happened here, but there appears to be no data loss.

**Comment by astronexus** [comment]
No sign of data loss with the missing IDs. It's possible that at some point, there was an erroneous row (e.g., a duplicate) that was deleted. 

Renumbering the catalog would break continuity with existing data references, so I am leaving these gaps in the ID sequence alone for now.
