### ISSUE TITLE
Van Maanen's Star has no constellation

### ISSUE THREAD

**Issue by isaac-ward** [astronexus/HYG-Database#25]
Row number 3822, Van Maanen's Star, does not appear to have a constellation. Should it be listed as belonging to Pisces?

![image](https://user-images.githubusercontent.com/30889042/144931445-95f3b297-87a2-498c-abff-0ce008da286c.png)

This is an excellent database btw!

**Comment by astronexus** [comment]
Constellations are generally available only for stars that exist in either HIPPARCOS or the Yale Bright Star Catalog. Stars only in the Gliese catalog don't have that information. Van Maanen's Star is one of the few stars only in Gliese.

**Comment by astronexus** [comment]
HYG v3.6 revisited missing constellations and added ones to all stars that were missing one before, including Van Maanen's star.
