### ISSUE TITLE
Identical split files in ATHYG v0.3, v1.0, v1.1

### ISSUE THREAD

**Issue by galliz** [astronexus/HYG-Database#29]
The -1 and -2 split files for certain versions v0.3, v1.0, v1.1 of the ATHYG catalog are identical upon decompression.

Affected files:
- athyg_v0_3-1.csv and athyg_v0_3-2.csv
- athyg_v1_1-1.csv and athyg_v1_1-2.csv
- athyg_v10-1.csv and athyg_v10-2.csv

**Comment by astronexus** [comment]
Verified; updating now.

**Comment by astronexus** [comment]
The v0.x public alphas have been obsolete for several months now and have been removed.
The v1.0 and v1.1 versions' second split file (...-2.csv) now has the expected data.
